title: SeanyDcode's Blog
author: Sean Dougherty
email: seanydcode@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first attempt at GitHub pages. Nice try!

# social links
twitter_username: @SeanyDcode
github_username:  @SeanyDcode

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
